###############

GPU: [0,1,2,3]

VERBOSE: True

MODEL:
  MODE: 'Denoising'
  SESSION: 'MIRNet'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: [4]
  NUM_EPOCHS: [60]
  LR_INITIAL: 2e-4
  #NEPOCH_DECAY: [40]
  #BETA1: 0.9

TRAINING:
  PATCH_SIZE: [128]
  NUM_WORKERS: [4]
  VAL_PS: 196
  RESUME: True
  TRAIN_DIR: './SIDD_patches/train' # path to training data
  VAL_DIR: './SIDD_patches/val'     # path to validation data
  SAVE_DIR: './checkpoints'          # path to save models and images
  SAVE_IMAGES: False
  #VAL_AFTER_EVERY: 1
